# Generated by Django 3.0.3 on 2021-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20200218_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
